feat: Add StepfunctionsStack for agent evaluation workflow
awslabs/agent-evaluation pull request #85
Opened 2024-09-24 12:48 UTC by ifeojo

*Issue #, if available:*

*Description of changes:*
feat: Add StepfunctionsStack for agent evaluation workflow

- Implement StepfunctionsStack with AWS CDK
- Add Lambda functions for various steps in the workflow:
  - generate_map
  - check_agent_status
  - create_alias
  - delete_alias
  - run_test
  - update_bedrock_agent
- Create Step Functions state machine for agent evaluation process
- Set up EventBridge rule to trigger workflow on S3 object creation
- Configure necessary IAM roles and permissions
- Implement error handling and retry logic in the state machine

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-02 13:33 UTC, sharonxiaohanli requested changes
Thank you for submitting the PR. Please add gitignore to ignore the cached files `__pycache__`.  We have code lint check in the CICD pipeline as well https://github.com/awslabs/agent-evaluation/blob/main/.github/workflows/ci.yml. Please make sure you run those commands locally and fix those formatting issues before submitting the PR.

2024-10-02 14:03 UTC, sharonxiaohanli requested changes

2024-10-02 14:03 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/functions/check_agent_status_1/.~c9_invoke_Zi2ZN1.py
what's this file for?

2024-10-02 14:03 UTC, sharonxiaohanli commented on stepfunctions/app.py
> +    env=cdk.Environment(region='us-east-1'),
is there a reason to hard code the region?

2024-10-02 14:05 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/agenteval/__init__.py
same here. why the agenteval core code is copied over? It should be used as an layer.

2024-10-04 16:02 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/functions/check_agent_status_1/index.py
> +# from aws_lambda_powertools import Logger, Tracer
For clean code, please remove those commented-out lines. But I think it's actually helpful to have the Logger from the powertool. And you can log `response` for any troubleshooting :). Not a blocking comment. I'll leave it to you to decide on the logging.

2024-10-04 16:02 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/functions/check_agent_status_2/index.py
> +# from aws_lambda_powertools import Logger, Tracer
same as above

2024-10-04 16:05 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/functions/create_alias/index.py
> +    print(alias_resp)
logger from the powertool produces cleaner logging format. If you decide to use powertools across all lambda functions, please make it consistent :)

2024-10-04 16:06 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/functions/delete_alias/index.py
> +    response = bedrock_agent.delete_agent_alias(
check the status of `response` and log error if needed before sending back `200`.

2024-10-04 16:06 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/functions/delete_alias/index.py
> +    #pass in from step function but for now
Can you elaborate in the comment about the TODO here?

2024-10-04 16:07 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/functions/generate_map/index.py
> +# from aws_lambda_powertools import Logger, Tracer
delete commented out lines or use logger from powertools to log

2024-10-04 16:08 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/functions/run_test/index.py
> +        # 'user_profile':{
delete the commented out lines.

2024-10-04 16:09 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/functions/run_test/index.py
> +    # finally:
delete commented out block.

2024-10-04 16:09 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/functions/run_test/index.py
> +    # finally:
delete commented out block.

2024-10-04 16:09 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/functions/update_bedrock_agent/index.py
> +    # role = "arn:aws:iam::905418302891:role/service-role/AmazonBedrockExecutionRoleForAgents_LED91O3XKK"
This line MUST be deleted :D .

2024-10-04 16:10 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/functions/update_bedrock_agent/index.py
> +
better to log out the response and add try/catch handler block.

2024-10-04 16:13 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/stepfunctions_stack.py
> +        # The code that defines your stack goes here
remove the commented out block

2024-10-04 16:14 UTC, sharonxiaohanli commented on stepfunctions/stepfunctions/stepfunctions_stack.py
> +        # first_choice_def = first_choice.when(condition1, wait_step.next(get_status_step_1).next(first_choice)).otherwise(update_agent_step).afterwards()
remove this line

2024-10-04 16:14 UTC, sharonxiaohanli commented on stepfunctions/tests/unit/test_stepfunctions_stack.py
> +#     template.has_resource_properties("AWS::SQS::Queue", {
remove the block.

2024-10-04 16:45 UTC, ifeojo commented on stepfunctions/stepfunctions/functions/update_bedrock_agent/index.py
> +    # role = "arn:aws:iam::905418302891:role/service-role/AmazonBedrockExecutionRoleForAgents_LED91O3XKK"
oops!!! :D

2024-10-04 17:36 UTC, sharonxiaohanli approved these changes
LGTM! Thank you for working on it

2024-10-04 17:36 UTC, merged